services:
  - type: web
    name: dbt-certification-quiz
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
    headers:
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /templates/*
        name: Cache-Control
        value: public, max-age=3600
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.png
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.jpg
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.ico
        name: Cache-Control
        value: public, max-age=31536000
    healthCheckPath: /healthz
    autoDeploy: true
